### ISSUE TITLE
Create standard function library

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#120]
In addition to the operators with specific syntax, there is a whole list of "normal" standard functions which are represented using their own ELM nodes. We need to create a "System" library with all these functions consisting of:

* https://build.fhir.org/ig/HL7/cql/09-b-cqlreference.html#logical-operators-3 (and further)
* https://build.fhir.org/ig/HL7/cql/16-i-fhirpathtranslation.html
* https://build.fhir.org/ig/HL7/cql/06-translationsemantics.html

Since the System library (much like the System types) is always "included" we do need to add some magic to make sure these are always in scope as well.

**Comment by ewoutkramer** [comment]
See also #95.

**Comment by EvanMachusak** [comment]
Is your intent to create a native CQL version of the implementation of the `ICqlOperators` interface?  Or will the functions be `external`?

**Comment by ewoutkramer** [comment]
@EvanMachusak did this in the cql2elm branch, closing.
