### ISSUE TITLE
Implicit DateIso8601 Converters

### ISSUE THREAD

**Issue by patburke234** [FirelyTeam/firely-cql-sdk#137]
**Describe the bug**
There's a strange developer usability issue with DateTimeIso8601.
 
In the DateTimeIso8601 class, there's an internal String constructor, we did this likely to keep people from using it. However, passing a string to the ctor is still semantically correct because there's an implicit operator override on DateIso8601 (no time) that converts string -> DateIso8601.
 
So, I have a datetime value as a string, I try to pass it to:
new DateTimeIso8601("2024-01-01T00:00:00")
 
This implicitly tries to convert it to a DateIso which fails since it has time values in the string. 

**To Reproduce**
new DateTimeIso8601("2024-01-01T00:00:00")

**Expected behavior**
Instantiation of a DateTimeIso8601

**Screenshots**
![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/2043585/055cf631-7c0e-4d97-896c-2b1f290170f0)

**Version used:**
 - Latest

**Comment by EvanMachusak** [comment]
I can see the value in declarations like this:
`DateIso8601 date = "2024-01-16";`
This, in particular, is similar to CQL's `@2024-01-16` shorthand for `Date(2024,01,16)` concept.

I think we have two directions we can take:

1) Implicit string-to-ISO conversions for Date, DateTime, and Time, which requires making the string ctors public to prevent the issue described here
2) Explicit string-to-ISO conversions and leave the string ctors private
3) Eliminate this implicit cast

If we go with option 1 or 2, we should fix the body of this operator to use TryParse.  Not sure why we would have two implementations that parse a string.

**Comment by ewoutkramer** [comment]
This "surprise" behaviour that Patrick described is exactly why I am using implicit operators very sparingly, especially on common types like strings. So I am not a fan of 1), and would like to do 3).  In the .NET SDK I would now use the "TryParse" pattern, so IsoDate.TryParse("string") - and not a constructor, since I don't like constructors to throw.

**Comment by EvanMachusak** [comment]
Agree.  We'll remove the implicit operator.

**Comment by patburke234** [comment]
https://github.com/FirelyTeam/firely-cql-sdk/pull/138
