### ISSUE TITLE
PackageCLI to take a command line argument to replace the cononical root url '#' with an actual value

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#151]
# Background
The PackageCLI generates library resources as json files (as described [here](https://firely.atlassian.net/wiki/spaces/CQLSDK/pages/1359085592/How+to+Running+VONK-5284-load-vs-cql+Branch#R4%5CDemo%5CPUT-Create-Library---AdultOutpatientEncountersFHIR4-2.2.000)). These files need to be manually updated before sending them to the Create Library endpoint on Firely Server. The url property starts with a # sign, and this needs to be replaced with the actual root url.

# Solution
Look at specs and update the PackageCLI to take an additional argument for the root uri and replace the # with that value if it is provided.

**Comment by ewoutkramer** [comment]
We can close this issue, right? PR has been merged?
