### ISSUE TITLE
Bump to .net8.0 and C#12

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#170]

**Comment by ewoutkramer** [comment]
This would mean we don't support net6 anymore, since we're not targeting netstandard2.1.   I tried targeting netstd2.1, but some of the AppDomain loading stuff is not available.

**Comment by alexzautke** [comment]
This shouldn’t be a huge issue because of the end of support for .NET 6, right?

**Comment by ewoutkramer** [comment]
Done.
