### ISSUE TITLE
Handling late-bound types - incorrect CQL or we need some more magic?

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#193]
QICoreCommon.cql contains this beauty in `ToAbatementInterval`:

```
else if condition.abatement is Interval<DateTime> then
	  Interval[condition.abatement.low, condition.abatement.high)
```

Our ExpressionBuilder chokes on this as, although the type of `abatement` is checked in the conditional, the type of the low/high of the constructed interval on the last line is unknown. An easy fix, that I applied is:

```
else if condition.abatement is Interval<DateTime> then
	  Interval[(condition.abatement.low as DateTime), (condition.abatement.high as DateTime))
```

which *does* work.  What are we supposed to do here?

* Fix the CQL,
* Assume the type of the `Interval` constructed is an interval of a choice type, in which all allowed types of `abatement` are allowed, and trust it to be cast to the correct type later on?
* Add a langugage feature to CQL to allow the compiler keep track of the conditional, so we know that `abatement` is of type `Interval<DateTime>` in this case?

**Comment by EvanMachusak** [comment]
We should be balloting the 3rd option:

- Add a langugage feature to CQL to allow the compiler keep track of the conditional, so we know that abatement is of type Interval<DateTime> in this case?

This happens in `case` statements too and confuses everyone.

**Comment by ewoutkramer** [comment]
Suggestion: do this based on Linq.Expression equivalence (aka compare Linq Expression DebugView).

**Comment by ewoutkramer** [comment]
But a more general comparer based on something like the ElmWalker would also be possible, and maybe more future proof.

**Comment by ewoutkramer** [comment]
In this specific case, I think this is a mistake in the CQL:

```
define function ToAbatementInterval(condition Condition):
	if condition.abatement is DateTime then
	  Interval[condition.abatement as DateTime, condition.abatement as DateTime]
	else if condition.abatement is Quantity then
		Interval[Patient.birthDate + (condition.abatement as Quantity),
			Patient.birthDate + (condition.abatement as Quantity) + 1 year)
	else if condition.abatement is Interval<Quantity> then
	  Interval[Patient.birthDate + (condition.abatement.low as Quantity),
		  Patient.birthDate + (condition.abatement.high as Quantity) + 1 year)
	else if condition.abatement is Interval<DateTime> then
	  Interval[condition.abatement.low, condition.abatement.high)
	else null as Interval<DateTime>
```

As we can see, on every `else if`, the author has explicitly added an `as`, except in the last case (which was probably added later).  I have for now just added the `as DateTime` in two functions in QICoreCommon.

The above conversation is still relevant - either the language should add a feature about deriving the type OR we should accept the type is `Interval<Choice<X,Y>>` - and actually construct that here by having support in C# for Choice<T>. I am ok to experiment with that at a later moment.

**Comment by ewoutkramer** [comment]
Closing this, as this covers the same ground as #198
