### ISSUE TITLE
Incorrect translation of binding name in QICore model?

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#194]
The CMS file `Status.cql` contains the following function:

```
 //Observation Vital Signs
define function "BloodPressure"(Obs List<"QICore.observation-bp">):
  Obs O
    where O.status in { 'final', 'amended', 'corrected' }
```

Note that here, `QICore.observation-bp` is used, not observation, and looking at its mapping in https://raw.githubusercontent.com/cqframework/clinical_quality_language/master/Src/java/quick/src/main/resources/org/hl7/fhir/qicore-modelinfo-4.1.1.xml, the status element maps to `QICore.Status`

```
      <element name="status" elementType="QICore.Status" target="%value.value" description="registered | preliminary | final | amended +" definition="The status of the result value." comment="This element is labeled as a modifier because the status contains codes that mark the resource as not currently valid." mustSupport="true">
         <binding name="Status" strength="Required"/>
      </element>
```

In contrast, in the base Observation in the QICore model, the type of this `status` element is actually `QICore.ObservationStatus`.

When the above CQL is translated to ELM, we find:

```
 "operand" : [ {
                     "locator" : "195:11-195:18",
                     "resultTypeName" : "{http://hl7.org/fhir}Status",
                     "path" : "value",
                     "type" : "Property",
                     "source" : {
                        "path" : "status",
                        "scope" : "O",
                        "type" : "Property"
                     }
```

The type has been translated to the FHIR binding `Status`, which is *not* the binding for `Observation.status` but the binding for `VerificationResult.status` -- causing a casting error in our ExpressionBuilder.

**Comment by ewoutkramer** [comment]
Raise this as a bug with Bryn.

**Comment by EvanMachusak** [comment]
Possible short term fix:
```
 //Observation Vital Signs
define function "BloodPressure"(Obs List<"QICore.observation-bp">):
  Obs O
    where ((O.status as Any) as FHIR.ObservationStatus) in { 'final', 'amended', 'corrected' }
 ```

or

```
 //Observation Vital Signs
define function "BloodPressure"(Obs List<"QICore.observation-bp">):
  Obs O
    where (ToString(o.Status) in { 'final', 'amended', 'corrected' }
```

**Comment by ewoutkramer** [comment]
See https://chat.fhir.org/#narrow/stream/179220-cql/topic/Translation.20of.20bindings

**Comment by ewoutkramer** [comment]
For now, I have added a manual mapping in `ChangeType()` in the ExpressionBuilder, which can correct these mistakes.
