### ISSUE TITLE
FHIRHelpers hack - how far do we go?

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#196]
We have special cases built-in for handling calls to the FHIRHelpers library.  Each of the functions we've encountered so far has manual handling in `GetFunctionRefReturnType`. Could we, with our current understanding, actually compile this file and refer to it, so we don't need to manually figure out the return types?

For now I have added:
* ToInterval - existed, but changed it so it will return Interval<DateTime> when we don't know the type statically (will need to revisit why the type is unknown there, probably because it is a property that is a choice element)
* ToValue - this returns a complex `Choice<all FHIR datatypes supported by function, Choice<all other types>>`.  For now I made it return `typeof(object)`, but what to do here?

**Comment by EvanMachusak** [comment]
This is supposed to be gotten from the modelinfo.  These are implicit conversions implemented through FHIRHelpers.

**Comment by ewoutkramer** [comment]
Ok, during our call we agreed we would add support for reaching out to dependent libraries from the ExpressionBuilder, so we can actually look this up in the compiled FHIRHelpers. This is also necessary to fix #195 .  And we can avoid having modelinfo this way.
