### ISSUE TITLE
Query results are demoted to singles too aggressively

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#197]
The current implementation of Query in the ExpressionBuilder demotes the result of a query to a single element if the source of the query is a non-list type. This implicitly implements automatic list-demotion which works well most of the time. However, this simplification is done even if the expected result of the query *is* a list, e.g. when compiling this line from CMS `AHAOverall`:

```
collapse (Event.dosageInstruction.timing.repeat.bounds DoseTime
                                        return DoseTime.toInterval())
```

the result of the nested query will be a single Interval (of DateTime), which is incorrect, since the `collapse` function requires a list as input. 

For now, if have stopped the Query translator from calling the `Single` operator if the required return type of the query indicates a list type.

**Comment by EvanMachusak** [comment]
The query code for list demotion is probably correct.  We probably missed the list promotion requirement.

What does the ELM say, and are we respecting it atomically?  e.g., if the Query's `resultTypeSpecifier` is a List, I would be surprised if we are not correctly returning a `List` type.  Is there a `ToList` anywhere (e.g., is the `collapse`'s operand a `ToList``)?

**Comment by ewoutkramer** [comment]
> What does the ELM say, and are we respecting it atomically?
 
It stated that the expected result was a List, that's why it was easy to fix for me, I just looked at the expected return type and the code no longer calls `Single` if the result is a List (and still does the old behaviour if it is not)

**Comment by ewoutkramer** [comment]
Fixed this for single source queries. Multi still to do.
