### ISSUE TITLE
Cleanup - DirectedGraph

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#202]
DirectedGraph does not have centralized state, the same state is stored in the graph and the node (forwarding edges).
There is also a lot of dead code that can be removed.

**Comment by EvanMachusak** [comment]
I'd recommend eliminating the Graph project entirely.  The only thing we really need is topological ordering.  We could probably do that better with a simple adjacency matrix or something.  There could be some lean NuGet packages out there that might give us what we need.

**Comment by baseTwo** [comment]
I only see this now. Yes, agree on getting rid of the graph library. I have some code ready which can do depth first and topological sort enumeration on any type without the need of a graph, I could create a new issue for this. I can also have a look what is out there already.

```csharp
public readonly record struct TraversalCallbacks<T>(
	Func<(T? Previous, T Current, T Next), bool>? AllowEnter = null,
	Action<(T? Previous, T Current)>? Enter = null,
	Action<(T? Previous, T Current)>? Exit = null)
{...}

public static class Traversal
{
	public static IEnumerable<T> DepthFirst<T>(
		T current,
		Func<T, IEnumerable<T>> getNextItems,
		TraversalCallbacks<T> callbacks = default,
		T? previous = default)
	{...}

	public static IEnumerable<T> TopologicalSort<T>(
		T current,
		Func<T, IEnumerable<T>> getNextItems,
		TraversalCallbacks<T> callbacks = default,
		T? previous = default)
	{...}
}
```

**Comment by EvanMachusak** [comment]
Yes, I have used similar approaches in the past to implement graph algos.  I'm not 100% sure where we'd put those extensions - possibly just in Cql.Abstractions.  That's an overarching project that both the compile-time and run-time projects need.
