### ISSUE TITLE
Time zone offsets are rendered as DateTimeOffsets incorrectly in some cases

### ISSUE THREAD

**Issue by EvanMachusak** [FirelyTeam/firely-cql-sdk#204]
In this HL7 test:

`ToDateTime('2014-01-01T12:05:05.955-01:15')`

The timezone offset is specified as `-01:15`, which should be `-75` minutes.  We are incorrectly creating the `DateTimeOffset` as `-45` minutes.  This happens [on this line](https://github.com/FirelyTeam/firely-cql-sdk/blob/9ccd27e8122679b888b5fd8c378b5b76343c1b2e/Cql/Iso8601/DateTimeIso8601.cs#L297).

Essentially, we are passing `offsetHour` as `-1` and `offsetMinute` as 15.  In the `TimeSpan` constructor, these two parameters are added together, e..g `-60 + 15` which results in -45 instead of -75.

**Comment by ewoutkramer** [comment]
Isn't this fixed by now? Since we're running all Hl7 tests "natively" now?

**Comment by baseTwo** [comment]
Had a look at these two tests

```cql
define "ToDateTime4":
  ToDateTime('2014-01-01T12:05:05.955+01:30')= @2014-01-01T12:05:05.955

define "ToDateTime5":
  ToDateTime('2014-01-01T12:05:05.955-01:15')= @2014-01-01T12:05:05.955
```

The assertions are incorrect and should look like this instead

```cql
define "ToDateTime4":
  ToDateTime('2014-01-01T12:05:05.955+01:30')= @2014-01-01T10:35.05.955

define "ToDateTime5":
  ToDateTime('2014-01-01T12:05:05.955-01:15')= @2014-01-01T13:20.05.955
```

**Comment by baseTwo** [comment]
Change priority to low

**Comment by baseTwo** [comment]
These tests are in `CqlTypeOperatorsTest.xml`

```xml
		<test name="ToDateTime4">
			<expression>ToDateTime('2014-01-01T12:05:05.955+01:30')</expression>
			<output>@2014-01-01T12:05:05.955+01:30</output>
		</test>
		<test name="ToDateTime5">
			<expression>ToDateTime('2014-01-01T12:05:05.955-01:15')</expression>
			<output>@2014-01-01T12:05:05.955-01:15</output>
		</test>
```

The assertions are correct and the tests are passing, so closing this ticket
