### ISSUE TITLE
Multi-source queries with singletons as source are not/not completely supported

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#220]
The `MultiSourceQuery()` function - much like the normal Query function in principle allows singletons to work as source, by wrapping them in an array. However, this wrapper code seems to come into play too late:

```csharp
        var multiSourceTupleType = TypeManager.TupleTypeFor(tupleSpecifier, ctx, (type) =>
                IsOrImplementsIEnumerableOfT(type)
                    ? TypeManager.Resolver.GetListElementType(type, true)!
                    : throw new NotSupportedException("Query sources must be lists."));
   
         var crossJoinedSource = CrossJoin(query.source!, multiSourceTupleType, ctx);
            var source = crossJoinedSource;

            var isSingle = false;
            if (!IsOrImplementsIEnumerableOfT(source.Type))
            {
                var arrayInit = Expression.NewArrayInit(source.Type, source);
                source = arrayInit;
                isSingle = true;
            }
```

We see code that calls `NewArrayInit` when the type does not implement IEnumerable, but already at the first lines (when `TupleTypeFor()` is called) we throw an exception because "Query sources must be lists". This means that code like

```

define "Urinary Symptom Score 6 to 12 Months After Initial BPH Diagnosis":
  Last("Urinary Symptom Score Assessment" USSAssessment
      with "Initial BPH Diagnosis Starts Within 6 Months Before or After Start of Measurement Period" InitialBPHDiagnosis
        such that months between start of InitialBPHDiagnosis.prevalenceInterval() and USSAssessment.effectiveDatetime in Interval[6, 12]
      sort by effectiveDatetime
  )

define "Urinary Symptom Score Change":
  from
    "Urinary Symptom Score Within 1 Month after Initial BPH Diagnosis" FirstUSSAssessment,
    "Urinary Symptom Score 6 to 12 Months After Initial BPH Diagnosis" FollowUpUSSAssessment
    let USSChange: FirstUSSAssessment.valueInteger - FollowUpUSSAssessment.valueInteger
    return USSChange
```

from UrinarySymptomScoreChangeAfterBenignProstaticHyperplasiaFHIR.cql does not compile:  `Urinary Symptom Score 6 to 12 Months....` does a `Last`, so returns a single value - which then breaks the multi source query in `Urinary Symptom Score Change`.

**Comment by EvanMachusak** [comment]
Makes sense.  HEDIS measures never touch this code because we forbid multi-source queries since they result in cross joins.

**Comment by ewoutkramer** [comment]
That's fine! I'll have to fix this for CMS though, including the nesting of `lets`, so a subsequent `let` can refer to a previous one (see #199, where I fixed this for single source queries).
