### ISSUE TITLE
Add back property init setters for vocab stuff

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#221]
I accidentally removed the public setters, but this means that generated code that constructs Codes etc cannot construct them anymore -- need to add the init setters back to make this work.

**Comment by EvanMachusak** [comment]
Example function:
```
define function ToValueSet(uri String):
    if uri is null then
        null
    else
        System.ValueSet {
            id: uri
        }
 ``` 

This applies to all of the CQL Primitives that are modeled as ClassInfo types:
Code
CodeSystem
Concept
Quantity
Ratio
ValueSet

**Comment by baseTwo** [comment]
Will have to pull in ModelInfo into the ExpressionBuilder. 

Look at support-contexts branch. Only works for Expressions at the moment

**Comment by baseTwo** [comment]
Opened, should be init, not set properties
