### ISSUE TITLE
Make sure the Cql Demo solution only uses publicly visible members

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#288]
In our work on 2.0, we might have misused the fact that the Demo libraries are friends to the CQL libraries, so they can use internal stuff. Remove that friendship and make sure everything needed for the Demo is public.

We might decide at this point to no longer support calling the Lambdas (Linq.Expression) directly, since we'd like to ditch that in a future version anyway.

**Comment by baseTwo** [comment]
Maybe even package the cql projects to local nuget packages, and include those into the Demo solution, and removing project references.

Remove the strong name signing of Demo projects in cql-demo.props. A note is attached in that file
