### ISSUE TITLE
Demo solution is missing an example of loading value sets which cause the demo methods not to work

### ISSUE THREAD

**Issue by EvanMachusakNCQA** [FirelyTeam/firely-cql-sdk#302]
In [MeasureTest](https://github.com/FirelyTeam/firely-cql-sdk/blob/develop/Demo/Test/MeasuresTest.cs), our code creates empty value sets.  This causes the measures not to work.  While debugging, this is fairly opaque and hard to understand.

**Comment by drivin-ncqa** [comment]
Added functionality to load value sets into the demo solution with BCS-E numerator check as an example.

[Link to PR](https://github.com/FirelyTeam/firely-cql-sdk/pull/316#event-12711467583)
