### ISSUE TITLE
2.0/CqlTypeToFhirTypeMapper for mapping between CqlCode and Coding is wrong

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-cql-sdk#340]
**Describe the bug**
[CqlTypeToFhirTypeMapper.cs#L122](https://github.com/FirelyTeam/firely-cql-sdk/blob/0e1ff194ccc78dcab1bbf8084ebb2f437fb136b8/Cql/Cql.Packaging/CqlTypeToFhirTypeMapper.cs#L122) should map a CqlCode to a Coding. You can see that the mapping is wrong as a FHIR Coding is mapped to a CqlCode.

**Comment by baseTwo** [comment]
Will fix in 2.0
