### ISSUE TITLE
2.0/Create alpha releases (for Firely Server CQL plugin)

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#364]
Create alpha releases (for Firely Server CQL plugin)
* Potentially downgrade C# Microsoft analyzers to be the same as FS, or make them private assets

**Comment by baseTwo** [comment]
I do not have the permission to create tags (see screenshot)

![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/4639799/c00937fd-69a4-4ae8-8306-776e65f04658)

**Comment by alexzautke** [comment]
@cknaap Do you have enough GitHub permission to give access to @baseTwo?

**Comment by baseTwo** [comment]
[Tag](https://github.com/FirelyTeam/firely-cql-sdk/compare/v1.0.0-rc1...v2.0.0-alpha) was created by @louisledev

**Comment by baseTwo** [comment]
2.0.0-alpha tag created and released
