### ISSUE TITLE
Use C# value tuples, instead of the generated tuples that went into a troublesome binary resource.

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#378]
Before starting trying to move the generated tuples into libraries, think about removing the need for them altogether and just use c# tuples if possible. Keep tuple "properties" alphabetical, so that the order they are used are always in sync when these properties disappear at runtime.

Think about generating the c# tuples at the point where the c# is generated first, to see if that works, and then later remove the generated tuples altogether

Also continue the conversation in zulip once merged.

Initiated from this conversation in [Zulip](https://chat.fhir.org/#narrow/stream/179171-dotnet/topic/Packaging.20of.20CQL.20and.20TupleTypes-Binary/near/439254291)
Related issues regarding tuples #378, #379, #380

**Comment by ewoutkramer** [comment]
This will fix the related #260, #379, #380 as well.
