### ISSUE TITLE
Solve to fix ExpressionBuilder when definitions are not in-order

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#397]
Predecessor issue #422 

* `ExpressionBuilderContext.InvokeDefinedFunctionThroughRuntimeContext` when definitions are out of order
* Fix unit tests - Find the `[Ignore("Will fix in https://github.com/FirelyTeam/firely-cql-sdk/issues/397")]` attributes from 4 unit tests and fix them

Check additional todo's  in Slack discussion : https://firelyteam.slack.com/archives/C05GW1J1HFV/p1721036253203929

**Comment by ewoutkramer** [comment]
We will implement this by visiting the ELM before we start processing it. Using the visitor + the recent LibrarySet resolver functions we can easily add `resultTypeSpecifiers` to all FunctionRefs.

**Comment by baseTwo** [comment]
Demo projects didn't build, work rolled back in PR #437

**Comment by baseTwo** [comment]
Reopened ticket as it is not merged yet #468

**Comment by baseTwo** [comment]
Added in the description that 4 unit tests must be un-ignored to truly test if this feature is working.
