### ISSUE TITLE
Standarize on dependency injection strategy

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#406]
Currently there are two dependency injection strategies: The .net way with the host builder, and the factories way currently in the 2.0 repo (types derived from `CqlFactoryBase`).

Only one should be used.

CQL to ELM testing uses ServiceProvider and built in the BaseTest class.

**Comment by EvanMachusak** [comment]
It seems to me that `CqlFactoryBase` is reinventing what .NET already ships standard that their core frameworks like ASP.NET use.  I don't see a reason to stray from the .NET BCL and invent our own.  What advantages does `CqlFactoryBase` offer?
