### ISSUE TITLE
Some external functions don't compile

### ISSUE THREAD

**Issue by EvanMachusak** [FirelyTeam/firely-cql-sdk#499]
This code:
```
library FuncTest version '1.0.0'

define function ToInteger(decimal System.Decimal) returns System.Integer: external
```
Causes a function to be created whose parameter name is `nullable_@decimal`, which is an invalid C# identifier.

**Comment by ewoutkramer** [comment]
@EvanMachusak - pretty sure I saw some code to fix this? Is there a PR?
