### ISSUE TITLE
Typeconverter is called for every new context (1.0)

### ISSUE THREAD

**Issue by DamienM419** [FirelyTeam/firely-cql-sdk#511]
When using context patient and creating a new context for each bundle datasource, the creation of the context is taking about 27% of the time for 100k patients. The reason for this is because in the FhirModelBindingSetup the FhirTypeConverter.Create occurs every time when it only needs to happen once and be passed into the constructor to be reused.

**To Reproduce**
Create a unit test with a batch of patient bundles and create new context in a parallel foreach, profile the unit test and you will see 1 line of code eating up most of the run time for the context creation.

**Expected behavior**
TypeConverter creation only needs to happen one time since it's related to the CQL and not the datasource.

**Screenshots**
![image](https://github.com/user-attachments/assets/c3c5b705-2834-46a5-9577-fb58d7120caf)

**Version used:**
 develop branch

**Comment by baseTwo** [comment]
@DamienM419 are you currently working on this? Would you mind assigning this ticket to yourself?

**Comment by ewoutkramer** [comment]
This is fixed *for 1.0* by #512 , so I suggest we keep this open until we have ported/reimplemented this fix for 2.0.

**Comment by baseTwo** [comment]
Creating a separate issue for 2.0 #586
