### ISSUE TITLE
Measure library creation overwriting the library resource file. Measure output incomplete.

### ISSUE THREAD

**Issue by richfirely** [FirelyTeam/firely-cql-sdk#516]
**Describe the bug**
When compiling libraries with the packager, if the library is also a measure, it will overwrite the FHIR library resource file. Measures should be written to a different filename or folder. ResourcePackager.cs CreateMeasureResource. 

We should also produce the full and correct measure FHIR resource.

**To Reproduce**
Compile elm that is both a library and a measure. Notice only the measure is created.

**Version used:**
2.0 branches.

⚠️ Must be discussed at September WGM as this is not per spec.

**Comment by baseTwo** [comment]
Reopened - see comments https://github.com/FirelyTeam/firely-cql-sdk/pull/531#issuecomment-2385481213
