### ISSUE TITLE
Remove IServiceProvider encapsulation and use GetRequiredService<T> only

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#526]
* Remove encapsulating service retrieval into a struct
* Remove DisposeContext in unit tests and improve lifetime cycle
* Rename Hosting namespaces

**Comment by EvanMachusak** [comment]
`DisposeContext` can be eliminated as well.  Microsoft's service dependency system calls `Dispose` when the scope that created them is disposed.

**Comment by EvanMachusak** [comment]
Also remove the `Hosting` namespace.  This has nothing to do with hosting.
