### ISSUE TITLE
Performance hit with numerous class initializations (1.0)

### ISSUE THREAD

**Issue by DamienM419** [FirelyTeam/firely-cql-sdk#547]
During a performance pass of develop branch for 1.0, I noticed that creating the instances and setting up classes was taking a lot of time and in most cases it took more time than the actual CQL execution.

![image](https://github.com/user-attachments/assets/781d159f-8a42-4d90-8eb0-e3f1b4a5d6a8)

Turning these into static would alleviate the setup time for the classes and improve execution time.

Note: Please assign this bug to me as I already have it fixed and add the label that this is for 1.0, not 2.0.

**Comment by DamienMosier** [comment]
PR with fix located here: #548

**Comment by DamienMosier** [comment]
When running all of our measures I noticed some measures that relied heavily on the caching took a huge performance hit. These are the execution time on all of our measures/decks on the same build machine for our nightly runs.

Before the singleton updates when we still had Lazy variables.

ADD-E: Duration: 57m 4s
CRE: Duration: 1h 41m 27s
PND-E: Duration: 44m 15s
SPD: Duration: 9h 24m 18s

After singleton

ADD-E: Duration: 3h 32m 35s
CRE: Duration: 2h 46m 1s
PND-E: Duration: 10h 48m 39s
SPD: Duration: 3h 10m 21s

Here is the total run time of all measures on our build machine.

Latest 1.0 with singleton changes

![Image](https://github.com/user-attachments/assets/aee4cf0e-266f-4003-9c81-576fb7fc3670)

I realized we needed an update to use scoped measures and singleton libraries. Here is the same run on our build machine with local changes in the engine to have both.

![Image](https://github.com/user-attachments/assets/a3dabb78-e0a4-4291-a27f-50d484a5d0c5)

ADD-E: Duration: 38m 0s
CRE: Duration: 57m 4s
PND-E: Duration: 53m 39s
SPD: Duration: 1h 36m 22s

As you can see, huge performance gains using singleton libraries to reduce the constructor initialization of all supporting libraries as well as improved performance to use caching/lazy variables inside the measure CQL to improve the performance when you write 1 CQL define that is used in multiple places, like a list of episode dates.
