### ISSUE TITLE
Plan DevOps for Integration Tests on Nightly Builds

### ISSUE THREAD

**Issue by baseTwo** [FirelyTeam/firely-cql-sdk#581]
Plan meeting with Louis/Marten. See related ticket on DevOps board https://firely.atlassian.net/browse/DEVOPS-281

**Comment by ewoutkramer** [comment]
* Discuss in Slack what we want this to look like
* Plan meeting with Louis/Marten to brief them on our requirements

**Comment by baseTwo** [comment]
Pipeline needs to be exactly like the .NET SDK
Add timestamp to 3rd part of version e.g. 2.0.7-alpha-yyyyMMdd.n (n is iteration for the day)

**Comment by baseTwo** [comment]
There are already nightly builds
