### ISSUE TITLE
Default value of type Period in Library has invalid syntax

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#60]
**Describe the bug**
When using a default value for a period, we will write an extension "https://ncqa.org/fhir/StructureDefinition/ext-parameter.cql-default-value to the Library.parameter" containing a period. Unfortunately, the timestamp for the parameter is formatted incorrectly: it does not have a "Z" suffix:

```
  {
          "url": "https://ncqa.org/fhir/StructureDefinition/ext-parameter.cql-default-value",
          "valuePeriod": {
            "start": "2019-01-01T00:00:00.000",
            "end": "2019-12-31T23:59:59.999Z"
          }
        },
```

**Comment by baseTwo** [comment]
@ewoutkramer , I need more context here. I tried adding a unit test (see associated branch)

**Comment by baseTwo** [comment]
This is ticket is a year old. Discussed with @ewoutkramer to close this, since it is probably not relevant. Couldn't find anything in the output resource files either.
