### ISSUE TITLE
Demo project does not build on non-Windows OS

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#61]
**Describe the bug**
We tried running the demo project on a Mac laptop, this is what we found:

* There is no `bin` directory included with the Maven distribution, and even if it was, we cannot use it on Mac.
* We got JNI errors until we ran the java bits on openJSK 17
* There are backward-slashed-paths everywhere in the csproj files and build targets.
* The PackagerCLI is invoked using `PackagerCLI.exe`, while this suffix does not work on Mac.
* The java classpath is using a wildcard (*), in which case the classpath needs to be quoted with single quotes on Mac.
*

**Comment by ewoutkramer** [comment]
Also, the solution still refers to the (local) project for Hl7.Fhir.R4 - it can be removed.

**Comment by ewoutkramer** [comment]
AssemblyCompiler.cs has a hard-coded "Tuples/" built in, should be 

`.Where(kvp => kvp.Key.StartsWith("Tuples" + Path.DirectorySeparatorChar));`

**Comment by ewoutkramer** [comment]
I pulled #86 so the maven binaries should no longer be a problem.

The rest still is.

**Comment by birick1** [comment]
Read the updates notes in #86.  

- I tested with OpenJDK (couple different versions, currently v20).  Downloaded from [Adoptium](https://adoptium.net/).  
- I haven't tried [AWS Corretto](https://aws.amazon.com/corretto/?filtered-posts.sort-by=item.additionalFields.createdDate&filtered-posts.sort-order=desc), but it probably would be fine too.

**Comment by baseTwo** [comment]
Old ticket, closing
