### ISSUE TITLE
Ensure that cqlType extension is added to all Library input parameters

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-cql-sdk#635]
**Describe the bug**
Currently the https://ncqa.org/fhir/StructureDefinition/ext-parameter.list-element-type is added also on non-repeating parameters. Make sure to add a [cqlType extension](https://hl7.org/fhir/uv/cql/conformance.html) to all **input and output** parameters of a Library.

![Image](https://github.com/user-attachments/assets/28bfad11-0147-40bf-88aa-3687762fa9b5)

**Comment by baseTwo** [comment]
@baseTwo  Reach out to Alexander to walk through the bug

**Comment by baseTwo** [comment]
Meeting [video](https://fhirly-my.sharepoint.com/personal/alexander_fire_ly/_layouts/15/stream.aspx?id=%2Fpersonal%2Falexander%5Ffire%5Fly%2FDocuments%2FRecordings%2FMeeting%20with%20Alexander%20Zautke%2D20241202%5F114614%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E71486431%2Dbbd6%2D4b47%2D9f78%2D121253b6843a&ga=1) with Alexander , starts at 6m 50s
