### ISSUE TITLE
Work on ANTLR grammar rules

### ISSUE THREAD

**Issue by ewoutkramer** [FirelyTeam/firely-cql-sdk#70]
We need to go over the rules in the CQL grammar one by one to make sure we
* Translate it correctly
* Make sure we've implemented the operator involved
* Test the translation by testing the produced Elm node.
* Test actually running an expression using the grammar piece

**Comment by ewoutkramer** [comment]
- [ ] definition
- [ ] library
- [ ] libraryDefinition
- [ ] usingDefinition
- [ ] includeDefinition
- [ ] localIdentifier
- [ ] accessModifier
- [ ] parameterDefinition
- [ ] codesystemDefinition
- [ ] valuesetDefinition
- [ ] codesystems
- [ ] codesystemIdentifier
- [ ] libraryIdentifier
- [ ] codeDefinition
- [ ] conceptDefinition
- [ ] codeIdentifier
- [ ] codesystemId
- [ ] valuesetId
- [ ] versionSpecifier
- [ ] codeId
- [ ] typeSpecifier
- [ ] namedTypeSpecifier
- [ ] modelIdentifier
- [ ] listTypeSpecifier
- [ ] intervalTypeSpecifier
- [ ] tupleTypeSpecifier
- [ ] choiceTypeSpecifier
- [ ] statement
- [ ] expressionDefinition
- [ ] contextDefinition
- [ ] functionDefinition
- [ ] operandDefinition
- [ ] functionBody
- [ ] querySource
- [ ] aliasedQuerySource
- [ ] alias
- [ ] queryInclusionClause
- [ ] withClause
- [ ] withoutClause
- [ ] retrieve
- [ ] contextIdentifier
- [ ] codePath
- [ ] codeComparator
- [ ] terminology
- [ ] qualifier
- [ ] query
- [ ] sourceClause
- [ ] letClause
- [ ] letClauseItem
- [ ] whereClause
- [ ] returnClause
- [ ] aggregateClause
- [ ] startingClause
- [ ] sortClause
- [ ] sortDirection
- [ ] sortByItem
- [ ] qualifiedIdentifier
- [ ] qualifiedIdentifierExpression
- [ ] qualifierExpression
- [ ] simplePath
- [ ] simplePathReferentialIdentifier
- [ ] simplePathQualifiedIdentifier
- [ ] simplePathIndexer
- [ ] simpleStringLiteral
- [ ] simpleNumberLiteral
- [ ] expression
- [ ] termExpression
- [ ] retrieveExpression
- [ ] queryExpression
- [ ] booleanExpression
- [ ] typeExpression
- [ ] castExpression
- [ ] notExpression
- [ ] existenceExpression
- [ ] betweenExpression
- [ ] durationBetweenExpression
- [ ] differenceBetweenExpression
- [ ] inequalityExpression
- [ ] timingExpression
- [ ] equalityExpression
- [ ] membershipExpression
- [ ] andExpression
- [ ] orExpression
- [ ] impliesExpression
- [ ] inFixSetExpression
- [ ] dateTimePrecision
- [ ] dateTimeComponent
- [ ] pluralDateTimePrecision
- [ ] expressionTerm
- [ ] termExpressionTerm
- [ ] invocationExpressionTerm
- [ ] indexedExpressionTerm
- [ ] conversionExpressionTerm
- [ ] polarityExpressionTerm
- [ ] timeBoundaryExpressionTerm
- [ ] timeUnitExpressionTerm
- [ ] durationExpressionTerm
- [ ] differenceExpressionTerm
- [ ] widthExpressionTerm
- [ ] successorExpressionTerm
- [ ] predecessorExpressionTerm
- [ ] elementExtractorExpressionTerm
- [ ] pointExtractorExpressionTerm
- [ ] typeExtentExpressionTerm
- [ ] powerExpressionTerm
- [ ] multiplicationExpressionTerm
- [ ] additionExpressionTerm
- [ ] ifThenElseExpressionTerm
- [ ] caseExpressionTerm
- [ ] aggregateExpressionTerm
- [ ] setAggregateExpressionTerm
- [ ] caseExpressionItem
- [ ] dateTimePrecisionSpecifier
- [ ] relativeQualifier
- [ ] offsetRelativeQualifier
- [ ] exclusiveRelativeQualifier
- [ ] quantityOffset
- [ ] temporalRelationship
- [ ] intervalOperatorPhrase
- [ ] term
- [ ] invocationTerm
- [ ] literalTerm
- [ ] externalConstantTerm
- [ ] intervalSelectorTerm
- [ ] tupleSelectorTerm
- [ ] instanceSelectorTerm
- [ ] listSelectorTerm
- [ ] codeSelectorTerm
- [ ] conceptSelectorTerm
- [ ] displayClause
- [ ] codeSelector
- [ ] conceptSelector
- [ ] keyword
- [ ] reservedWord
- [ ] keywordIdentifier
- [ ] obsoleteIdentifier
- [ ] functionIdentifier
-

**Comment by baseTwo** [comment]
Since all HL7 tests are passing it is assumed all is implemented
