### ISSUE TITLE
Demo project missing Maven binaries

### ISSUE THREAD

**Issue by birick1** [FirelyTeam/firely-cql-sdk#75]
**Describe the bug**
According to [Getting started with the Firely SDK CQL repository](https://github.com/FirelyTeam/firely-cql-sdk/blob/develop/docs/getting-started.md), building the Demo project is all that is necessary to get going.  In particular, a [full install of Maven](https://github.com/FirelyTeam/firely-cql-sdk/blob/develop/docs/getting-started.md#:~:text=To%20make%20this%20easier%2C%20the%20solution%20contains%20a%20full%20install%20of%20Maven%2C%20plus%20the%20necessary%20build%20targets%20to%20run%20them.%20The%20first%20time%20you%20run%20the%20build%2C%20it%20will%20also%20download%20all%20the%20necessary%20Java%20CQL/ELM%20tools.) should be present in the repository, and there is a build task called [Download CQL to ELM CLI via Maven](https://github.com/FirelyTeam/firely-cql-sdk/blob/develop/Demo/Cql/Build/Cql.Targets.xml).

However, the `bin` folder in the path `Demo\Cql\Build\apache-maven-3.8.8\bin\mvn` of the build task is not present in the repo.  So upon attempting to build, the following error occurs:

![image](https://github.com/FirelyTeam/firely-cql-sdk/assets/109760379/5b464a14-df4b-4092-96cb-554044dfa9c5)

**To Reproduce**
Confirm the `Build\apache-maven-3.8.8\bin` folder is missing in the repo.

**Expected behavior**
Add the `bin` folder to the repo so that a build error does not occur.  

Alternatively, list Java (the build task already implicitly assumes java is installed with a correct `%PATH%`) and Maven as external prerequisites and change the build task to use `mvn` relying on the `%PATH%` having been set in the user's operating system.  In other words, 

1. Change `<Exec Command="Build\apache-maven-3.8.8\bin\mvn -f Build\pom.xml dependency:copy-dependencies"></Exec>` to `<Exec Command="mvn -f Build\pom.xml dependency:copy-dependencies"></Exec>`
2. Remove the `Demo\Cql\Build\apache-maven-3.8.8` folder and rely on the user to install Maven correctly with `%PATH%` already set.

**Comment by birick1** [comment]
Just read through #61 and looks like same root cause as first bullet in that issue.  

However, in my case, I am using a Windows machine.

**Comment by ewoutkramer** [comment]
Yes, this stuff was not checked into the repo in the end due to the git config ;-)

**Comment by ewoutkramer** [comment]
And it's a pain to get to work on a Mac.

**Comment by ewoutkramer** [comment]
Fixed in #86.

But not the slashes.

**Comment by ewoutkramer** [comment]
We'll pick the rest up in #61.
