### ISSUE TITLE
Inconsistent behavior with "in" operator

### ISSUE THREAD

**Issue by DamienM419** [FirelyTeam/firely-cql-sdk#78]
The following CQL code behaves differently when a ValueSetFacade is passed in and when a `List<Code>` is passed in. 

**To Reproduce**

define fluent function "Code in"(coding FHIR.Coding, codes List<System.Code>):
    coding in codes

The C# falls into context.Operators.CodeInList() function and it behaves differently for ValueSetFacade and `List<Code>`. When ValueSetFacade is passed in, only the code & system are checked. When a `List<Code>` is passed in then the code, system, version and display are checked.

**Expected behavior**
The function should behave the same. There needs to be a way to specify that you want the CodeInList operator to behave like Equivalent and not Equals.

**Comment by ewoutkramer** [comment]
@DamienM419 - does #79 fix this? Can I close this issue?

**Comment by DamienM419** [comment]
@ewoutkramer yes that PR fixes this issue and can be closed.
